### ISSUE TITLE
the details page link broken

### ISSUE THREAD

**Issue by andre-amorim** [RandomSanityProject/RandomSanityProject.github.io#3]
the link on
[index.md](https://github.com/RandomSanityProject/RandomSanityProject.github.io/blob/master/index.md)
called [details page](https://github.com/RandomSanityProject/RandomSanityProject.github.io/blob/master/details) is returnig error 404.
I think it refers to 
https://github.com/RandomSanityProject/RandomSanityProject.github.io/blob/master/details.md) 
the extension .md is missing ;-)

**Comment by gavinandresen** [comment]
githup pages runs the .md files through Jeckyll, which does magic and turns them into HTML pages with no extension.

https://www.randomsanity.org/details is working fine for me with both Chrome and curl; if it is still broken for you, please open a new bug with details on what browser you're using.
